import * as React from 'react';
import { Icon } from '@iconify/react';
import Box from '@mui/material/Box';
import type { SxProps, Theme } from '@mui/material/styles';

import iconMap from './icon-map.json';
import { IconSize, nodeClassNames, nodeClassValue } from './spec';
import { resolveNodeIcon, type NodeIconInput } from './resolveNodeIcon';
import { resolveModelStateIcon, type ModelStateInput } from './resolveModelState';

/**
 * The single place icons are chosen and rendered.
 *
 * Why it exists: the same concept used to pick its own icon in each file, so the
 * address-space tree showed a node one way and the model view another. Nothing outside
 * this directory should import an icon package directly.
 *
 * See ./spec.ts for the sizing and container rules, ./icon-map.json for the concept ->
 * name mapping shared with the Blazor/ASP.NET applications, and ./resolveNodeIcon.ts
 * for how a node's TypeDefinition selects its glyph.
 */

/**
 * MUI's SvgIcon sizes, so `fontSize` keeps meaning what it did at the ~130 call sites
 * that pass it. 'inherit' tracks the surrounding text, which is what icons inside
 * Typography need.
 */
const fontSizes = { small: 20, medium: 24, large: 35, inherit: '1em' } as const;

/** MUI's SvgIcon `color` values, mapped onto palette paths. */
const colors = {
   inherit: 'inherit',
   action: 'action.active',
   disabled: 'action.disabled',
   primary: 'primary.main',
   secondary: 'secondary.main',
   error: 'error.main',
   info: 'info.main',
   success: 'success.main',
   warning: 'warning.main',
} as const;

export interface SymbolProps {
   /** One of IconSize, in px. Wins over `fontSize`. */
   size?: number;
   /** MUI SvgIcon-compatible sizing. */
   fontSize?: keyof typeof fontSizes;
   /** MUI SvgIcon-compatible colouring. */
   color?: keyof typeof colors;
   /** Accessible name. Omit for icons that merely decorate adjacent text. */
   title?: string;
   /** MUI SvgIcon's name for the same thing; accepted so call sites did not have to change. */
   titleAccess?: string;
   sx?: SxProps<Theme>;
}

export interface RawSymbolProps extends SymbolProps {
   /** Iconify name, e.g. 'material-symbols:folder-outline-rounded'. From icon-map.json. */
   name: string;
}

/**
 * Renders one Material Symbol. Wrapped in a Box so colour comes from `sx`/inheritance
 * like any other MUI element, and so the glyph sits on the text baseline instead of
 * nudging the line box.
 */
export const Symbol: React.FC<RawSymbolProps> = ({
   name, size, fontSize, color, title, titleAccess, sx,
}) => {
   const label = title ?? titleAccess;
   return (
      <Box
         component={Icon}
         icon={name}
         sx={{
            flex: '0 0 auto',
            fontSize: size ?? fontSizes[fontSize ?? 'medium'],
            width: '1em',
            height: '1em',
            ...(color ? { color: colors[color] } : null),
            ...sx,
         }}
         aria-hidden={label ? undefined : true}
         aria-label={label}
         role={label ? 'img' : undefined}
      />
   );
};

/**
 * One component per concept in icon-map.json's `ui` section. Each is a thin wrapper so
 * a concept can never drift from the shared map, and so swapping icon sets stays a
 * change to the JSON plus this file. Written out literally rather than generated by a
 * factory so react-refresh can recognise them as components.
 */
const ui = iconMap.ui;

/**
 * Node-kind icons, sourced from the same `nodeIcon` entries the tree resolves against —
 * so a "create a data variable" button and a data variable in the tree are the same
 * glyph by construction, not by two entries that happen to agree. These used to be
 * separate `ui` concepts (dataObject, label, functions) that duplicated these names.
 */
const node = iconMap.nodeIcon;

export const ObjectIcon: React.FC<SymbolProps> = (p) => <Symbol name={node.object} {...p} />;
export const InterfaceIcon: React.FC<SymbolProps> = (p) => <Symbol name={node.interfaceType} {...p} />;
export const DataVariableIcon: React.FC<SymbolProps> = (p) => <Symbol name={node.dataVariable} {...p} />;
export const PropertyIcon: React.FC<SymbolProps> = (p) => <Symbol name={node.property} {...p} />;
export const MethodIcon: React.FC<SymbolProps> = (p) => <Symbol name={node.method} {...p} />;

/**
 * Model lifecycle state, from icon-map.json's `modelState` section. Separate concepts from the
 * `ui` action icons even where a glyph coincides — ModelPrivateEditableIcon shares
 * editDocument's glyph today, and the separate keys mean changing one later cannot silently
 * change the other.
 */
const modelState = iconMap.modelState;

export const ModelPrivateEditableIcon: React.FC<SymbolProps> = (p) => <Symbol name={modelState.privateEditable} {...p} />;
export const ModelPrivateLockedIcon: React.FC<SymbolProps> = (p) => <Symbol name={modelState.privateLocked} {...p} />;
export const ModelSharedIcon: React.FC<SymbolProps> = (p) => <Symbol name={modelState.shared} {...p} />;
export const ModelCloudLibraryIcon: React.FC<SymbolProps> = (p) => <Symbol name={modelState.cloudLibrary} {...p} />;

export const AddIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.add} {...p} />;
export const ArrowBackIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.arrowBack} {...p} />;
export const ArrowBackIosIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.arrowBackIos} {...p} />;
export const ArrowForwardIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.arrowForward} {...p} />;
export const AutoFixHighIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.autoFix} {...p} />;
export const CallSplitIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.callSplit} {...p} />;
export const CancelIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.cancel} {...p} />;
export const CategoryIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.category} {...p} />;
export const CheckIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.check} {...p} />;
export const ChevronRightIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.chevronRight} {...p} />;
export const CloseIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.close} {...p} />;
export const ContentCopyIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.contentCopy} {...p} />;
export const DarkModeIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.darkMode} {...p} />;
export const DeleteIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.delete} {...p} />;
export const DescriptionIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.description} {...p} />;
export const DownloadIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.download} {...p} />;
export const EditDocumentIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.editDocument} {...p} />;
export const EditIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.edit} {...p} />;
export const EmailIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.email} {...p} />;
export const ErrorOutlineIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.error} {...p} />;
export const ExpandMoreIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.expandMore} {...p} />;
export const FactCheckIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.factCheck} {...p} />;
export const FilterCenterFocusIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.filterCenterFocus} {...p} />;
export const FolderIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.folder} {...p} />;
export const HelpOutlineIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.help} {...p} />;
export const HistoryIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.history} {...p} />;
export const HomeIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.home} {...p} />;
export const InfoOutlinedIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.info} {...p} />;
export const KeyboardArrowDownIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.keyboardArrowDown} {...p} />;
export const KeyboardArrowUpIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.keyboardArrowUp} {...p} />;
export const ListAltIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.listAlt} {...p} />;
export const LockIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.lock} {...p} />;
export const LockOpenIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.lockOpen} {...p} />;
export const LoginIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.login} {...p} />;
export const LogoutIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.logout} {...p} />;
export const MenuIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.menu} {...p} />;
export const MoreHorizIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.moreHoriz} {...p} />;
export const MyLocationIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.myLocation} {...p} />;
export const PersonIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.person} {...p} />;
export const PlayArrowIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.playArrow} {...p} />;
export const PlaylistAddIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.playlistAdd} {...p} />;
export const RefreshIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.refresh} {...p} />;
export const RestartAltIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.restartAlt} {...p} />;
export const SchemaIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.schema} {...p} />;
export const ScienceIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.science} {...p} />;
export const SearchIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.search} {...p} />;
export const SubdirectoryArrowRightIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.subdirectoryArrowRight} {...p} />;
export const TaskAltIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.taskAlt} {...p} />;
export const UploadFileIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.uploadFile} {...p} />;
export const VisibilityIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.visibility} {...p} />;
export const VisibilityOffIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.visibilityOff} {...p} />;
export const WarningAmberIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.warning} {...p} />;
export const WidgetsIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.widgets} {...p} />;
export const AccountTreeIcon: React.FC<SymbolProps> = (p) => <Symbol name={ui.accountTree} {...p} />;

/**
 * The one exception to "no icon package outside this file": Material Symbols carries
 * no brand marks, so the Microsoft sign-in button keeps MUI's logo glyph.
 */
export { default as MicrosoftIcon } from '@mui/icons-material/Microsoft';

// Types only. The resolver functions stay importable from './resolveModelState' directly --
// re-exporting them here would make this a mixed module and break fast refresh, which is why
// resolveNodeIcon is not re-exported either.
export type { ModelState, ModelStateInput } from './resolveModelState';

export interface ModelStateIconProps extends ModelStateInput {
   /** One of IconSize. Defaults to IconSize.inline. */
   size?: number;
   /** Accessible name — pass the same wording the row's tooltip uses. */
   title?: string;
   sx?: SxProps<Theme>;
}

/**
 * One model's lifecycle state as an icon — private and editable, private and locked, shared,
 * or the Cloud Library copy. Titled so the state reaches hover and assistive tech, since the
 * glyph alone does not say it.
 */
export const ModelStateIcon: React.FC<ModelStateIconProps> = ({
   isPrivate, isEditable, origin, size = IconSize.inline, title, sx,
}) => (
   <Symbol
      name={resolveModelStateIcon({ isPrivate, isEditable, origin })}
      size={size}
      title={title}
      sx={sx}
   />
);

export interface NodeIconProps extends NodeIconInput {
   /** One of IconSize. Defaults to IconSize.inline. */
   size?: number;
   /** Renders at half opacity — used for nodes outside the active namespace. */
   dimmed?: boolean;
   sx?: SxProps<Theme>;
}

/**
 * The glyph for an address-space node — the same one in the tree, the model view and
 * the detail header. Titled with the NodeClass so the kind reaches hover and assistive
 * tech, since the glyph alone is not self-describing.
 */
export const NodeIcon: React.FC<NodeIconProps> = ({
   nodeClass, icon, size = IconSize.inline, dimmed = false, sx,
}) => {
   const cls = typeof nodeClass === 'number' ? nodeClass : nodeClassValue(nodeClass);
   return (
      <Symbol
         name={resolveNodeIcon({ nodeClass, icon })}
         size={size}
         title={nodeClassNames[cls] ?? 'Unknown'}
         sx={{ opacity: dimmed ? 0.5 : 1, ...sx }}
      />
   );
};
